### ISSUE TITLE
ArrayIndexOutOfBoundsException adding BlockChangeNotifier listener

### ISSUE THREAD

**Issue by ChloeDawn** [HellFirePvP/ObserverLib#2]
**ObserverLib version:** 1.16.4-1.5.1
**Crash report:** https://gist.github.com/ChloeDawn/a9621737ef8dbb8ceb1c7b0d4b5f1482

https://github.com/HellFirePvP/ObserverLib/blob/2c8422513904050a916fc323e43bc636aecf4333/src/main/java/hellfirepvp/observerlib/common/event/BlockChangeNotifier.java#L21-L26

**Comment by ChloeDawn** [comment]
I think this may be caused by `listeners`/`addListener` not being synchronized?

**Comment by HellFirePvP** [comment]
Concurrency derp. Will be fixed with 1.16.5 - 1.5.2
